parameters:
    locale:                 'en'
    uploads:                '%kernel.project_dir%/public/uploads/'
    artefact_uploads:       '%kernel.project_dir%/public/uploads/artefact/'
    corolla_uploads:        '%kernel.project_dir%/public/uploads/corolla/'
    corolla_recognizer_dir: '%kernel.project_dir%/src/Corolla-recognizer/'

services:
    _defaults:
        autowire:      true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:  '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags:     ['controller.service_arguments']

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    App\Mail\NotificationMailManager:
        arguments:
            $host:            '%env(MAILER_HOST)%'
            $port:            '%env(MAILER_PORT)%'
            $encryption:      '%env(MAILER_ENCRYPTION)%'
            $defaultFromName: '%env(MAILER_DEFAULT_FROM_NAME)%'
            $gmailUsername:   '%env(MAILER_GMAIL_USERNAME)%'
            $gmailPassword:   '%env(MAILER_GMAIL_PASSWORD)%'